### ISSUE TITLE
Remove the target subdirectory checkin

### ISSUE THREAD

**Issue by DePaul-KenYu** [chaseraab/CakeBook#3]
Looks like you need a .gitignore file to ignore files and subdirectories.  For example, target subdirectory should not be checked in.  

1) Update the .gitignore to ignore this directory.  See https://github.com/shinabro/DePaul-SE452/blob/master/.gitignore for reference

2) You will also need to remove the directory, there is a series of commands on git
Remove directory using below command from the root of the project folder
$git rm -r target

Committing the changes after removing the directory:
$ git commit -m “Code Folder removed”

Again running the push command
$ git push origin master

**Comment by okasten-depaul** [comment]
Thank you for bringing this up! Handling in PR https://github.com/chaseraab/CakeBook/pull/4
